[package]
name = "no_std_test"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { path = "./skyline" }
skyline_smash = { path = "./skyline_smash" }

