[package]
name = "skyline-rs-template"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git" }

[profile.dev]
opt-level = 0               # Use slightly better optimizations.
debug = 2
panic = "abort"

[profile.release]
panic = "abort"
