name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Docment API
      run: |
        cargo doc --target x86_64-unknown-linux-gnu --target-dir .
        rm -rf ./doc ./debug
        cp ./x86_64-unknown-linux-gnu/doc ./doc -r
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
